### ISSUE TITLE
Shouldn't need to specify +c/+j/+o for interfaces

### ISSUE THREAD

**Issue by j4cbo** [dropbox/djinni#1]
Right now interfaces can be {Java,ObjC}->C++ or C++->{Java,ObjC}, but the same interface can't be *both*, and the role is fixed at codegen time. We should be more flexible.

**Comment by mknejp** [comment]
I'm not 100% sure I agree with this. It seems at first to make sense, however this only really applies to C++ code because the same type can be used both-ways. However in both Java and Objective-C (or more specifically Android and Cocoa) there is a clear idiom what to use for which direction of information flow.

Concrete types are implemented with `class`/`@interface` and callback or delegate types with `interface`/`@protocol`. For one, it is the only way to implement something akin to multiple inheritence, and tw,o it makes it clear in what direction information flows.

I think keeping up with this idiom is a good idea. +c interfaces fill the role of concrete classes and are more like a `class`/`@interface` where as +o +j interfaces are more likely to be used as callbacks or delegates and go more in line with `interface`/`@class`. This separation makes it easier to explain to people how to use the generated types as they follow the conventions used in those frameworks/languages. It furthermore gives even *more* flexibility because the Java/Obj-C developers can for themselves determine how to integrate these interfaces in their type system.

**Comment by j4cbo** [comment]
So here are my current thoughts on this:

- The original phrasing of this bug is wrong. We actually do want to specify which sides an interface is implemented on, since the resulting code is sometimes different, e.g. `protocol` vs `class` after the recent refactor. And there's no need to spit out code to go in both directions if only one is used.
- But, we do need the ability to have an interface that's `+c +j +o`. (There's at least one place in Carousel where we fake this with two nearly-identical interfaces, one `+c` and one `+j +o`, and a lot of glue code to use the right one. It's ugly.) There's already support for bidirectional interface translation and wrapping/unwrapping in Java - see b08c54a0caad27ee144ade35a57f60cf4485ed8f .

Since the direction has changed, I'm closing this and have opened #81.

**Comment by cakoose** [comment]
I think having to declare `+c`/`+j`/`+o` is mental overhead.  I guess you have to weigh this mental overhead against the advantages we get:
1. We can generate different APIs for `+o` vs `+o +c`..
2. The code can be more efficient if we know that it's just `+o` or just `+j`.

*Generating different APIs*: At a high level it seems better to generate the same API for `+o` and `+o +c +j`.  For example, let's say you have a `+o` interface.  Later on, you realize you need to implement it on the C++ side and change it to a `+o +c` interface.  This breaks existing code.  Also, there's only one style do document and only one style for users to be aware of.

Again, I'm not familiar with the specifics, so maybe there's a strong reason to continue generating two different APIs (strong enough to justify the overhead of `+c`/`+j`/`+o`).

*Efficiency*: There are runtime efficiency considerations and code size considerations.  I haven't looked at this in a while, but I vaguely remember the runtime efficiency difference to be small when compared with the JNI overhead.  Not sure what the situation is for Objective-C.

For space efficiency, it's a matter of how much dead code the build process can eliminate.  Again, I only vaguely remember the details, but I think it's not straightforward to automatically eliminate unused JNI glue code from the final build.  This adds bloat to the APK.  Unused Java classes won't be JITed (I don't think, at least), so there's no memory cost there.  But unused C++/JNI code still takes up space in memory.

But I guess my broader point is that the `+c`/`+j`/`+o` thing is placing a higher burden on the programmer to make up for a deficiency in the build process.  And that's a reasonable position to take, but I wouldn't consider it ideal.

*Summary*:  I think the goal described in the bug is a good one.  But I'm also fine closing the bug since a bug tracker may not be the right place to track these vague/long-term things.  And supporting `+c +j +o` interfaces is a useful step towards that goal, so I think we're in good shape.
