### ISSUE TITLE
(Android-JNI) Cannot call java method from c++ if we're not in the main thread.

### ISSUE THREAD

**Issue by fredrod** [dropbox/djinni#141]
When the c++ try to call a java method from a new thread the app crash since the new thread is not attached to the VM. 

I've been able to make my app work by editing djinni_support.cpp::jniGetThreadEnv() to attach my thread to the vm if it's not attached. Do you have a better solution for this ?

Here's my updated version of jniGetThreadEnv.
```c++
JNIEnv * jniGetThreadEnv() {
    assert(g_cachedJVM);
    JNIEnv * env = nullptr;
    const jint get_res = g_cachedJVM->GetEnv(reinterpret_cast<void**>(&env), JNI_VERSION_1_6);
    if (get_res == JNI_EDETACHED) {
        if (g_cachedJVM->AttachCurrentThread(&env, NULL) != 0) {
          // :(
          std::abort();
        }
    } else if (get_res != JNI_OK) {
        // :(
        std::abort();
    }

    return env;
}
```

Thanks !

**Comment by mknejp** [comment]
Problem is you never detach from the thread. That can leak memory and potentially other resources.

I think a better solution is to incorporate this into your API and call the attach/detach methods at controlled moments in your application. If you are using something like a thread pool, create the threads in Java and pass them over to C++ where they get added to the pool. This also usually helps with debugging because the JVM has created those threads.

**Comment by fredrod** [comment]
Ok, i'll find a way to make sure that the threads from the pool are all attached and will detach them before destroying them. Thank you!

**Comment by j4cbo** [comment]
Yep, we suggest just creating threads on the Java or ObjC side. There's some example code for that here: https://github.com/dropbox/djinni/tree/master/extension-libs/platform-threads
