### ISSUE TITLE
How do I specify that record implements an interface?

### ISSUE THREAD

**Issue by vi** [dropbox/djinni#164]
```
somerecord = record +c {
    ololo : string;
    qqq : i64;
}

valueable = interface +c {
    getvalue () : i64;
}
```

C++ implementation ties together `somerecord` and `getvalue`.

How do I make `getvalue` callable from Java like a method?

**Comment by artwyman** [comment]
Depending on what you're actually trying to do, the answer is either "unsupported" or "it just works". :)

"Unsupported" answer: There's no way in Djinni to declare that a record implements an interface or the reverse.  They are unrelated types.

"It just works" answer: In C++ specifically, since you're using a custom extended record, you could do it with multiple inheritance:

    class SomeRecord : public SomerecordBase, public Valuable { ... };

Only C++ code can take advantage of that fact, though, and when your record is passed through Djinni to another language it will still be copied into a new record object in that language, which will be unrelated to the interface.

**Comment by vi** [comment]
I'm trying to do this:

```
somerecord = record +c {
    ololo : string;
    qqq : i64;
}

anotherrecord = record +c {
    id : i32;
}

toxml = interface +c {
    toxml(): string;
}

handlerecord = interface +c {
    handle(r : toxml);
    static createmyhandler(): handlerecord;
}
```

```c++
class Somerecord : public SomerecordBase, public Toxml ...;
class Anotherrecord : public AnotherrecordBase, public Toxml ...;
```

```java
Somerecord sr;
Anotherrecord ar;
Handlerecord h;
h.handle(sr);
```

It almost builds, except of Java don't konw that the records are actually also Toxml.

What is the best way to work around or redesign this?

**Comment by vi** [comment]
Found workaround:

```
toxml = interface +c {
    toxml(): string;
    static castFromSomeRecord   (sr : somerecord   ) : toxml;
    static castFromAnotherRecord(ar : anotherrecord) : toxml;
}
```

But that looks inconvenient.

**Comment by artwyman** [comment]
Yeah, that's probably as good a workaround as you're going to find with the current Djinni functionality.  Djinni doesn't know anything about the multiple-inheritance relationships you're setting up in C++, so neither does Java.  An alternative approach is to move away from records entirely and just make an interface with accessors like get_ololo() and get_qqq().  However without interface inheritance that kind of an approach won't scale well to many related types.
