### ISSUE TITLE
Creating Java interfaces objects in C++

### ISSUE THREAD

**Issue by awhlee** [dropbox/djinni#168]
Hi,

I'm new to Djinni so please excuse my basic question.  I'm trying to create an interface that is instantiated in C++ but implemented in Java.  I have this in my Djinni file:

PlatformNetworkService = interface +j {
    makeRequest(url: string): string;
}

In the other direction, it seems like the standard convention is to create a static factory function to instantiate the object in Java when it is implemented in C++.  I tried putting a static "createInstance" function on this interface:

PlatformNotificationService = interface +j {
    static createInstance(): PlatformNotificationService;
    notifyOfChange(): i32;
}

But I get an error "static not allowed for +j or +o interfaces".  I feel that I'm overlooking something really basic.

Please advise how to create Java interface objects in C++.  Thanks in advance.

**Comment by awhlee** [comment]
The default constructor in the C++ implementation is declared private so I can't use that.

**Comment by awhlee** [comment]
In the sample code, it seems that the interface that is implemented in Java or Obj-C is passed as a parameter to the static factory function of the C++ class and that is how the C++ code can use that interface.  It doesn't instantiate its own instance but uses the reference that it was provided.  I guess that is the design that needs to be followed?

**Comment by artwyman** [comment]
Yes, you're right.  Static methods only go in one direction currently (implemented in C++).  Usually in Djinni apps Java/ObjC is what starts first, and its first interaction with C++ is to call a static method on a +c interface.  That method can both take any necessary +j +o interfaces as an argument, and create a +c interface to return for use in future calls, so that you don't need to rely on global variables to store all your state.

**Comment by awhlee** [comment]
Thanks!
