### ISSUE TITLE
Problem running djinni on ubuntu

### ISSUE THREAD

**Issue by cuongtong** [dropbox/djinni#172]
Hi guys,

Great work on djinni and thank you for sharing this project. I've been trying to generate the project files on ubuntu but ran into some issues. 

When I ran `make example_android` I got the following error:

    dirname: missing operand
    Try `dirname --help' for more information.
    ./example/run_djinni.sh
    Already up to date: Djinni
    Parsing...
    Resolving...
    Generating...
    Copying generated code to final directories...
    djinni completed.
    ANDROID_BUILD_TOP= deps/gyp/gyp --depth=. -f android -DOS=android -Icommon.gypi         example/libtextsort.gyp --root-target=libtextsort_jni
    /bin/sh: 1: deps/gyp/gyp: not found
    make: *** [GypAndroid.mk] Error 127

Interestingly, under djinni folder, there's a gyp folder that looks like so gyp folder. 

when I ran `make example_ios` i got the following

    xcodebuild -workspace example/objc/TextSort.xcworkspace \
               -scheme TextSort \
               -configuration 'Debug' \
               -sdk iphonesimulator
    make: xcodebuild: Command not found
    make: *** [example_ios] Error 127

At least this generates a build_ios folder and there are xcodeproject in there. 

Is there any HOWTO or walk through on how to get the example project generated in linux (ubuntu)

Note: in the example folder, djinni generates `djinni-output-temp` which has all the generated files for cpp,java, jni and objc along with the gen.stamp. 

Thanks

**Comment by artwyman** [comment]
Most of the examples and tests are designed to run on OS X only, which is the platform we develop on at Dropbox.  Only a subset are runnable on Linux, which is used by some developers in the community.

Djinni itself can build and run on Linux just fine, and I'm pretty sure that the example_localhost target will work on Linux.  In the test-suite directory, the java test suite should be Linux compatible.

The Android example could theoretically run on Linux, though I don't know if it's been tested or debugged there.  The problem you showed above looks to be because you don't have ndk-build in your PATH.  The iOS build isn't ever going to work on Linux, since Apple doesn't allow building for iOS on non-Apple platforms.

**Comment by cuongtong** [comment]
I gave up generating the projects on Ubuntu and Windows (with Cygwin) . I ended up with generating the projects on osx. 

Having said that,  I was able to get djinni to compile on ubuntu. 

Thanks for your help!
