### ISSUE TITLE
Calling back into Java from other threads

### ISSUE THREAD

**Issue by jefftrull** [dropbox/djinni#176]
I ran into an interesting issue today with calling back Java interfaces from non JVM attached threads.

There's a common pattern in asynchronous programming where you have a pool of worker threads handling the results of previous requests as they arrive.  We are using a third-party library that does this; the workers are executing previously stored callbacks which are `std::shared_ptr<Callback>`, where Callback is an interface generated by Djinni.  Unfortunately the call hits the code in jniGetThreadEnv() which aborts if the JVM getEnv() call fails, which it will when a thread (such as the workers created by the library) is not attached to a JVM already.  We worked around it like this:

```
-    const jint get_res = g_cachedJVM->GetEnv(reinterpret_cast<void**>(&env), JNI_VERSION_1_6);
+    jint get_res = g_cachedJVM->GetEnv(reinterpret_cast<void**>(&env), JNI_VERSION_1_6);
+    if (get_res == JNI_EDETACHED) {
+        // attach this thread to the JVM
+        get_res = g_cachedJVM->AttachCurrentThread(&env, nullptr);
+    }
```

but it seems a little hacky.  Any thoughts on a better approach?  Thanks!

**Comment by artwyman** [comment]
We avoid C++-created threads calling into Java because that situation can call other issues beyond thread attach.  Specifically the thread may not use the right class loader, such that calls into Java might fail to find a class they need.  I think there might also be a risk of resource leakage when attached threads terminate, but I'm not sure of that.

I can't fully describe exactly what the issues are and how to avoid them, since we decided early on to avoid the situation entirely.  There's some sample code in djinni/extension_libs for the platform threads interface we use to let C++ create threads by calling into Java.  Of course, your 3rd-party library might not let you control thread creation, in which case you'd need to either post to another thread which was created by Java, or do the attach and deal with any fallout (pre-loading classes might be enough).

If you're going to do the attaching, then your approach seems reasonable.  The other alternative I'd see would be to just always call AttachCurrentThread, which should be a nop on an already-attached thread, and will give you the env.  I'm not sure I'd want to make this approach part of the mainline Djinni code without opt-in configurability, and/or some way to deal with detaching threads.

**Comment by jefftrull** [comment]
OK, thanks for the advice!
