### ISSUE TITLE
ObjcProxyCache fails to distinguish two protocols implemented in the same class

### ISSUE THREAD

**Issue by tiwoc** [dropbox/djinni#179]
## Description
When implementing two `+o` interface types in the same Objective-C class and then storing the same Objective-C object in C++ variables of both types, C++ code that calls methods of the `+o` interfaces will always call the methods of the first interface type that it has seen.

I don't know how I should make this description clearer because I didn't understand the failure mode completely, but please have a look at the example below which should make things clear.

## Affected versions of Djinni
This bug has been introduced with revision b0e3923 and is still present in the current master (163fbe4). Revision 2895f8f is the last version that works fine.

## Example
I have the following simple Djinni IDL file (scroll to the bottom of this post for a link to the full example project):

    FooListener = interface +o {
        foo();
    }

    BarListener = interface +o {
        bar();
    }

    Caller = interface +c {
        static initWithFooListener(fooListener: FooListener, barListener: BarListener): Caller;
        callFoo();
        callBar();
    }

The implementation of `Caller` is straightforward:

    class CallerImpl : public Caller {
    public:
        CallerImpl(const std::shared_ptr<FooListener> &fooListener, const std::shared_ptr<BarListener> &barListener)
        : fooListener(fooListener), barListener(barListener)
        {}

        void callFoo() override {
            fooListener->foo();
        }

        void callBar() override {
            barListener->bar();
        }

    private:
        std::shared_ptr<FooListener> fooListener;
        std::shared_ptr<BarListener> barListener;
    };

    std::shared_ptr<Caller> Caller::initWithFooListener(const std::shared_ptr<FooListener> &fooListener, const std::shared_ptr<BarListener> &barListener) {
        return std::make_shared<CallerImpl>(fooListener, barListener);
    }

I then implemented `FooListener` and `BarListener` in the same Objective-C class:

    @interface Listener : NSObject <EXFooListener, EXBarListener>

When I now construct an instance of `Listener`, pass it to the `Caller` initializer and then call `callBar()`, `foo()` is called instead of `bar()`.

Also check out my [full example project](https://github.com/tiwoc/djinni-cache-bug-demo).

**Comment by artwyman** [comment]
Thanks for reporting.  This has been reported before, but apparently never made it into a GitHub issue after discussion on Slack.  This is a limitation of the design of the proxy cache, which uses object identity as the lookup key.  The right answer is probably to add the interface type to the lookup key, perhaps via typeinfo.  Until that's done, the workaround is to create dedicated listener objects which can implement one interface at a time.

Pull requests are welcome if you want to take a stab at fixing this.  Otherwise I hope to get it fixed eventually, but it's not an immediate priority.

**Comment by tiwoc** [comment]
I'm looking into it. Could you point me to the Slack discussion? I scanned the #djinni channel but couldn't find it.

**Comment by artwyman** [comment]
Sorry, I misremembered, and was thinking of a discussion on the internal Dropbox Slack.  Here's a paste of my analysis from then (which doesn't really add much more than I said above).  Michael is one of our iOS developers who saw a bug with the wrong interface's method being called.  J4cbo is the one who implemented the proxy cache:

>Having thought about this some more, I'm pretty sure it's an unintended design limitation of the proxy cache.  The key to the map is the object, but the value is a type-erased proxy object, and the proxies are interface-specific.  I think what you're seeing is a proxy with one kind of vtable being treated as a different type, so what's getting called is is the method in the same slot from the other vtable.

>Michael, what you should do for now is avoid implementing more than one interface on the same object.  J4cbo, I think the fix here would be to get the interface into the hash key, perhaps via typeid(C++ABC).

**Comment by j4cbo** [comment]
As the person responsible for the proxy cache monstrosity, here's my recollection...

The proxy cache erases types, so there's only one per direction (one map for C++->ObjC, one map for ObjC->C++, another two for going between C++ and Java, etc). Because of the possibility of multiple inheritance, though, this is no good for ObjC, in exactly the way you're seeing.

I think ObjC classes implementing multiple protocols is the only way in which this can currently cause breakage, though we'd also run into problems in the future if we changed the Java codegen to emit interfaces instead of abstract classes. I think we're safe on the C++ side, since the different bases of a multiply-inheriting object will have different addresses.

So there are two possible fixes:
a) Add a `std::type_index` component to the key that the wrapper cache uses. This isn't that hard and I have a half-baked implementation almost ready to submit for review.
b) Split the wrapper cache so a different map exists for each type of object. This involves considering some other tradeoffs. I definitely *do* want to keep the type erasure, since at Dropbox there was significant code size blowup that resulted from instantiating `std::unordered_map` for each type of interface in the program. We'd also want to try to reduce, where possible, the number of places in which `<unordered_map>` has to be included, since there are compilation speed implications to that. Option (b) would also mean that the wrapper cache map has many separate mutexes instead of one big one, which would be a performance improvement as core counts increase.

So (a) is more expedient (patch nearly ready, if we decide that's the road to go down). (b) is harder, and a win in some ways (removes a multicore bottleneck), but a likely loss in others (compilation speed).

Thoughts?

**Comment by artwyman** [comment]
I'm in favor of A if it'll get done soon, with B as nice-to-have in future.
Also, it seems like the compile speed issue would be solvable so long as you can accept a tiny run-time hit in lost inlining.  Since you're type-erasing down to a single unordered_map instantiation, just wrap it in a non-template class and put the implementation in the cpp file.  Run-time overhead might just be an extra function call, or might be larger if the prior code was taking heavy advantage of inlining.  Hard to be sure without measuring.

**Comment by j4cbo** [comment]
Proposed fix here: https://github.com/j4cbo/djinni/tree/typetag

Andrew, can you review and double-check and see if this works with internal code too?

**Comment by artwyman** [comment]
Sure, though I don't promise to do it immediately.  I'm on vacation until 1/4, and currently in Mexico with slow internet.

**Comment by tiwoc** [comment]
Thanks a lot! I'll try it out and contribute some tests when I'm back at my work computer in the next few days.

**Comment by tiwoc** [comment]
j4cbo's fix works great, thanks a lot. I extended the test suite as promised to include a test that fails without the fix, but works when it is applied (the latter is the case in this branch):
https://github.com/tiwoc/djinni/tree/typetag-tests

**Comment by artwyman** [comment]
Okay, sorry for the delay, but I've tried this out now.  I haven't reviewed the code in detail, but it seems to work for our existing code (so, no regressions, but no validation of the new feature).  Carousel is happy with it on iOS and Android.

Some feedback and suggested next steps:

@j4cbo: On a quick through the interface/impl headers, I saw a few cases of weird formatting (extra indents after template<>, and wonder about the lack of variable names in new declarations.  Otherwise looks good, but I'll need to look at the other support lib changes more later.  Can you rebase/merge with the latest master, and then send a PR for me to review?

@tiwoc: Your tests look good, though I had to hack around a naming conflict of your foo_listener with another such listener in the Python tests (not on master branch yet).  Any chance you could do a clean rename of that?  Also would you be interested in filling in the tests in other directions?  I.e. it's possible to implement 2 different interfaces on the same C++ object, then pass it to ObjC or Java.  It's not possible to implement 2 interfaces on one Java object, since we use ABCs not Java interfaces.

Either way, in order to integrate your code I'll need you to sign our CLA here: https://opensource.dropbox.com/cla/
Once that's done you can send a PR after J4cbo's, or I or J4cbo can just cherry-pick your changes directly.

**Comment by j4cbo** [comment]
I made some of the changes in Xcode, so I may have been bitten by its
overenthusiastic indenting of namespaces... Will double check everything
and send a PR in the next few days.

**Comment by tiwoc** [comment]
Thanks. I'll update the tests and do a PR based on j4cbo's PR when it's ready.

**Comment by tiwoc** [comment]
I just submitted PR #186 which rebases my tests on j4cbo's PR and should resolve the naming conflicts.

What I haven't added are tests for the opposite direction, as I couldn't come up with a test that fails without the type tags.

**Comment by artwyman** [comment]
It wouldn't be bad to have tests to validate that the multi-interface feature works for C++ today, and continues to work tomorrow, even if it worked yesterday too. :)

I guess on the C++ side casting the same object to different interface types results in distinct pointers (because of separate vtables) so the problem doesn't exist because the notion of "object equality" doesn't go beyond pointer equality.  So Objective-C is really the only issue we're fixing for now.  Java could have such an issue if we used interfaces rather than base classes.  Python will certainly have the same issue once it adopts the proxy cache.  And C++ could have some related issues if we started supporting inheritance of interfaces.  All of which is me arguing to myself that it's probably still worth including the type information in the proxy cache on all platforms for future-proofing.
