### ISSUE TITLE
Memory issue

### ISSUE THREAD

**Issue by jacobjiangwei** [dropbox/djinni#195]
If app layer native ios view controller set one of the djinni class as delegate, I can see it's share_ptr like this:

        std::shared_ptr<::XXX::ISettingViewModelDelegate> cppDelegate = ::XXX::ISettingViewModelDelegateObjcProxy::iSettingViewModelDelegateWithObjc(delegate);

Then the memory shared_ptr is strong reference, not as usual in iOS , delegate should always be weak point.

That create a problem, memory objects are all hold each other, even the view controller are dismissed, the view controller still a strong reference of one instance of C++ object.

How to resolve this issue?

**Comment by mknejp** [comment]
It's not possible to have a weak reference from C++ directly into Java or Objective-C due to how the language translation works.

The way I solve this problem is to have a proxy class that has a weak reference on the Objective-C side.

```
class_with_delegate = interface +c {
  set_delegate(delegate: delegate);
}
delegate = interface +o+j {
  foo();
}
```

```objc
// This goes to C++
@interface MyDelegateProxy : NSObject<Delegate>
@property (nonatomic, weak) MyDelegate* delegate; // Note "weak" here
- (void)foo;
@end

@implementation MyDelegateProxy
- (void)foo {
  // And forwards all calls to the real thing
  [self.delegate foo];
}
@end

@interface MyDelegate : NSObject<Delegate>
@property (nonatomic) ClassWithDelegate* thing;
// This is the real delegate implementation
- (void)foo;
@end
```
You pass `MyDelegateProxy` to `thing` and make it point back to `MyDelegate` doing the actual work. That breaks the retain cycle. It's a bit more typing but so far the best solution I came up with.

**Comment by artwyman** [comment]
Agreed that the best (only) way to do weak references is to do them with an extra layer in one language or the other.  Djinni only does strong ownership through the language boundary, and doing otherwise is probably infeasible, since the semantics of "weak" references in different languages are too different to be compatible.

**Comment by pvaibhav** [comment]
Hi all, I'm wondering if it's not possible to simply pass a weak reference when assigning the delegate?

```
__weak Delegate* weak_delegate = actual_delegate;
[ClassWithDelegate setDelegate:weak_delegate];
```
and just use a `shared_ptr` on the C++ side so that the proxy exists, but what it points to might have been released. C++ thinks it's always holding a reference and goes about its merry ways.

Luckily, a released object becomes `nil` which can accept any messages sent to it without a crash. This simulates the behaviour you'd get in plain ObjC if you call methods on a weak delegate that was already released.

In my quick test, it seems to work. The ObjC object was released, and there was no crash when C++ called a method on it anyway.

**Comment by jacobjiangwei** [comment]
Correct above

**Comment by artwyman** [comment]
I'm not sure how that works.  If the method -[ClassWithDelegate setDelegate:] is Djinni-generated, and expects a strong reference as an argument, but you pass it a weak reference, won't it just be upgraded to strong at the call-site?  I'd be interested to see your actual complete code if you've found something which works.  In your example above you're calling setDelegate: as if it's a class method not an instance method, so that doesn't precisely match Miro's example above.  Also it's unclear if your "quick test" is using Djinni's generated code as-is, or if you're experimenting with modifying the generated proxy code to hold a weak reference.  I'm guessing the latter.

If you could somehow fool Djinni into taking a weak ref and putting it into the proxy object (the C++ object which holds on to the ObjC pointer and forwards methods), I think you might have problems with the re-use of proxy objects.  If the same ObjC object is passed through to C++ strongly, and the pointer values are the same, then you could end up re-using the original proxy object, with its weak reference, not providing the expected semantics.  Maybe not important to your use case, but could be a surprise in general.  If you wanted to generalize this, I think you'd need Djinni to be aware of strong/weak semantics so as to provide different proxies.

Perhaps more importantly, since this solution depends on the dangling-nil semantics in ObjC it's not clear to me that it could work bi-directionally, let alone work for Java or Python.  It's probably possible for Djinni's proxies to be extended to provide explicit strong/weak semantics in all languages, but I wouldn't expect it to be trivial.  I'd be excited to see a PR about it, though.

**Comment by pvaibhav** [comment]
@artwyman  You're right, my 'quick test' was flawed. Friday evening brain freeze.

I was directly assigning a newly-created object to a `__weak` pointer in ObjC, then passing that to djinni-generated `setDelegate:`. But the object was immediately released already and so `setDelegate:` was receiving `nil` in the first place. Assigning a preexisting (strong) pointer to a weak one and passing that, as you explained, does upgrade it to strong on djinni's side.

Oh well.. I'll be investigating this more, possibly with changes to djinni generated code itself. A significant chunk of my code needs to be asynchronous and I really don't want to be hand-generating wrappers for each delegate :)

**Comment by artwyman** [comment]
I answered a similar question on StackOverflow last week if it's useful: https://stackoverflow.com/questions/46717563/djinni-pointers-and-circular-references-between-c-and-swift-objective-c-java/46723404#46723404

But yes, it does require some extra classes to do this right.  We've found it's a bit more annoying in ObjC to deal with the extra "listener" objects, because it doesn't have the ability to create anonymous classes inline as Java does.

**Comment by pvaibhav** [comment]
Thanks for the hints. I'm guessing this issue crops up sooner or later for everyone. May I suggest adding this info to the Readme.md?

**Comment by artwyman** [comment]
It's certainly a question which has come up multiple times.  I think the README shouldn't go deep into patterns and practices, but an explicit mention that Djinni's references are strong, and that weak-references across languages won't work wouldn't be out of place.  Feel free to send a proposed PR for discussion.
