### ISSUE TITLE
JniClass<C>::allocate not being called

### ISSUE THREAD

**Issue by AFacchi** [dropbox/djinni#209]
First of all thanks guys for coming up with this tool. Yesterday I watched the CppCon talks and I wanted to try it out. I think the project is great.

So I compiled a HelloWorld dll in Visual Studio 2015.

My Visual studio project is something like this:
**HelloWorld_Cpp_Lib**: Hand coded HelloWorld.cpp class implementation
**Djinni_Support_Lib**: djinni_main.cpp and djinni_support.cpp compiled in a static library
**HelloWorld_Jni_dll**: NativeHelloWorld.cpp generated JNI code compiled in a dynamic library linked against the other two

The IDL used to generate the code is this one:
```
hello_world = interface +c {
	static create(): hello_world;
	get_hello_world(): string;
}
```
My Java code creates a HelloWorld class (using HelloWorld.create()) and calls the getHelloWorld() member function that returns a string. This example is taken from the first tutorial.

When I run the example in Java I get the following exception
![image](https://cloud.githubusercontent.com/assets/17490146/13347259/921cc0d4-dca7-11e5-8d4a-630f46918127.png)

The code that is referencing is this one:
![image](https://cloud.githubusercontent.com/assets/17490146/13347280/b5415fde-dca7-11e5-9fe6-8c5d3054aa75.png)

From my understanding JniClass<C> is templated on the HelloWorld class and creates a singleton with a std::unique_ptr pointing to that HelloWorld object. It seems however that JniClass::allocate is not called and the app crashes.

Do I need to call explicitely JNI_OnLoad (and JNI_OnUnload)? Reading the support_main.cpp doc 
```
// This provides a minimal JNI_OnLoad and JNI_OnUnload implementation - include it if your
// app doesn't use JNI except through Djinni.
```
I will not be using JNI except through Djinni, so I understand that I have to "include it". That file is being compiled and liked in the Djinni_Support_Lib. 

Could I get some guidance to understand what is happening and how to solve it?

**Comment by mknejp** [comment]
The problem is that the `JNI_OnLoad` and `JNI_OnUnload` functions in **Djinni_Support_Lib** are not part of the final DLL if it's a static library. You either add these two exported functions to your **HelloWorld_Jni_dll** and call them inside the static lib, or you make **Djinni_Support_Lib** a DLL so they are exported and called automatically when you load the library in Java. You can also create a `*.def` file for your **HelloWorld_Jni_dll** and add the two symbols there if you don't want to make Djinni a DLL (but you probably should in case there are multiple DLLs using it).

**Comment by AFacchi** [comment]
Hi @mknejp, thanks a lot for your help. I just had to added support_main.cpp to my DLL and it worked.
