### ISSUE TITLE
Selectively omit languages for record types

### ISSUE THREAD

**Issue by mrdomino** [dropbox/djinni#211]
Background: I'm currently trying to deal with a memory allocation problem -- I have an app that streams lots of sampled data from C++ -> Java in the form of arrays of doubles. Allocating a new ArrayList<Double> for every sample is killing performance by causing the GC to run way too often.

I want to work around this by writing a custom Java implementation of my record type that returns double[] rather than ArrayList<Double>. Then (since I can mutate the values without allocating new memory) I want to manage those arrays with a free pool. I want to do this while still keeping the autogenerated djinni code for Objective-C and non-Android C++.

The way I'm currently trying to tackle this is by defining a custom extern type and more or less copying and pasting the old autogenerated code into it for the other languages, but this seems really lame. What I'd like is to be able to tell djinni "only generate C++ <-> Objective-C for this record. I'll take care of the C++ <-> Java side."

Is there any way of doing this? record +j is not what I want; it creates a base class that has members that I won't use.

Also, to zoom out a bit (and since I know of no other forum for this at the moment), has anyone ever solved a problem like this before? What did you do?

**Comment by artwyman** [comment]
There's no current way to generate Java and C++ without generating JNI, or to generate different types for both.  Sounds like you don't want to generate Java for the record either, though?  But then how will Djinni know what code to call to generate method cals to interfaces which pass your record as an argument?

You're right that "record +j" is designed for a different use case.  It's for extending a record with additional methods, not for re-implementing the data marshalling.

I can think of two approaches to getting the customization you want.  The cleanest is probably to use external type support for Java, but not for ObjC, which you could accomplish by running the generator twice with two slightly different Djinni files.  Run once for Java using an external-type definition of your record (and discard the resulting C++ code).  Then run again for ObjC with a standard record.  Your two Djinni files can @import all the common details, other than the definition of the relevant type.  If this works, I could see some way to turn it into a standard feature with conditional definitions of the same type in a Djinni file or somesuch.

**Comment by mknejp** [comment]
If the `--jni-out` option is omitted the JNI generator isn't enabled. However you won't be able to use the type in any other interfaces or records.

I also think the cleanest option is to define an external type, but I wouldn't special-case it for Java but use it for both platforms instead. If performance is an issue it will also be an issue in Objective-C due to all the boxing allocations in `NSArray`. So in your case I would define a "buffer" type that is able to share memory between the languages. Create/reuse a `vector<double>` in C++ and pass the content to Objective-C using `[NSMutableData dataWithBytesNoCopy:length:freeWhenDone:]` and to Java using `NewDirectByteBuffer`, giving you a `java.nio.ByteBuffer` where you the `getDouble(int)` method gives you access to the content.
