### ISSUE TITLE
Why does record correspond to a struct in C++

### ISSUE THREAD

**Issue by davidchappelle** [dropbox/djinni#215]
Seems like a mistake to represent records as structs in C++. Is there any good reason for this? If not, can we switch them to be classes.

**Comment by j4cbo** [comment]
Yes, this is intentional and correct. It's a common idiom to use `struct` for objects that just carry data rather than implementing functionality. For example:
https://google.github.io/styleguide/cppguide.html#Structs_vs._Classes
http://llvm.org/docs/CodingStandards.html#use-of-class-and-struct-keywords
