### ISSUE TITLE
Crash with support-lib as shard lib

### ISSUE THREAD

**Issue by vrabeux** [dropbox/djinni#217]
My project consists on two shared libraries that use the same libsupport. I set it up as this : 
- libsupport-lib.so
- libfoo.so
- libbar.so

I am getting this crash on Android :

```
./support-lib/jni/djinni_support.hpp:238: static const C& djinni::JniClass<C>::get() [with C = djinni_generated::NativeBarClassForConfiguration]: assertion "s_singleton" failed
```

When linking everything staticaly it works well. But, lib foo and bar have big code base and do not follow the same development cycle. It would make more sens to have shared libraries. Is this supported ? Is my setup wrong ? Did I forget something ?

**Comment by artwyman** [comment]
So, the symptom here is a static variable not having been initialized (djinni_generated::NativeBarClassForConfiguration::s_singleton in this case).  Djinni uses some template magic in static construction to populate class info which is needed during marshalling/unmarshalling.  There's code run from JNI_OnLoad() which sets things up.  I can see two possible causes to investigate, in order of complexity.

1) Make sure you're running the code of Djinni's default JNI_OnLoad(), either by including the cpp file directly, or by calling the relevant init code yourself.

2) I've seen static constructors not get executed if the class which contains them isn't listed at the top-level when building the .so in the NDK (i.e. not taken from a separate shared library).  I think without this the variables, or their files, might be considered unused.

3) If this is really related to the multiple .sos, then it might be the case that thanks to template instantiation, you're getting multiple copies of the static member variable.  It's possible the init code is setting up the variable in one library, but then a later access is using the uninitialized copy of it in a separate library.  If this is your root cause, it might be tricky to work around.  I suspect it's possible but can't give any guidance.  I've never tried separating the Djinni support lib into a different library from the generated code.

**Comment by vrabeux** [comment]
Thanks for the quick reply. 
* For 1) => Yes. just tested and Djinni's JNI_OnLoad is called.
* For 2) => Not sure to follow. But If I understand well, Yes, this classes are built at top level. 
* For 3) => We could maybe verify this by removing one of the library ?

**Comment by artwyman** [comment]
If you're using NDK's Android.mk, 2) means the generated cpp files are listed in LOCAL_SRC_FILES  in the same component as "include $(BUILD_SHARED_LIBRARY)", not a separate library makefile.

If 3) is what's going on, I'm not sure of the right fix, other than linking everything together into a single library.  I presume that libfoo.so and/or libbar.so are make use of support-lib functionality in libsupport-lib.so, so it couldn't just be removed.  And if my guess is correct, one of the copies of the static variable is in libsupport-lib.so, and the other is in whichever lib is using it.
