### ISSUE TITLE
JNI possible issues in multithread envinroments and exceptions

### ISSUE THREAD

**Issue by steweg** [dropbox/djinni#238]
Hello all,

during our usage of djinni, we come across issue, which is related to multi-thread environments. Based on my understanding in JNI, this is highly problematic staff, especially when threads are created by C++ side. In our app we have one main thread with many async-task threads (all created within C++). The problem is those async-task threads. Their purpose is to simply run one method implemented on Java side. Once done, they are destroyed. According to colleagues of mine this is buggy as there is no DetachCurrentThread method called

In order to allow proper usage we needed to adjust djinni code with this [support-lib.patch](https://github.com/dropbox/djinni/files/317989/support-lib.patch.txt)
And adjust the API of that specific JNI interface after djinni generation with this [myInterfaceA.patch](https://github.com/dropbox/djinni/files/317999/myInterfaceA.patch.txt)

After that it works quite well. As I am not JNI expert, so I rather left it for others to judge whether or not it is valid bug/point. I also think that we might workaround this problem by using thread-pools, where threads might not be created/destroyed during normal run-time, but we didn't had yet time to test this theory.

We also notice that when we are handling exceptions coming from JAVA in C++ there is no meaning full data in it (what() API is simply saying "std::exception", nothing more). This doesn't provide any kind of data for troubleshooting of what went wrong, especially in case when C++ developer is complaining about this to Java developer. In order to fix that we come with this [jni_exception.patch](https://github.com/dropbox/djinni/files/318040/jni_exception.patch.txt)
This allows C++ side to at least log what happened and that makes the troubleshooting much more easier.

**Comment by mknejp** [comment]
We cannot really put `DetachCurrentThread()` anywhere to make it operate reliably because Djinni doesn't know when threads are created or destroyed. This issue comes up repeatedly and so far nobody has proposed a fix that works in every situation.

Besides, creating new threads for every task is really frickin' wasteful. I suggest to use a thread pool. I have a library [here](https://github.com/mknejp/schedulers) that offers thread pools that can be used both by C++ and Java (as `java.util.concurrent.Executor`) sharing the same threads and it's taking care of attaching/detaching the JVM. It also has `.yaml` files to integrate into other Djinni projects.

For the exceptions I think you'll have to make a pull request with added tests showing how the change influences the generated code and the properties of the generated exceptions.

**Comment by steweg** [comment]
I agree with you, thread pool seem to be the best option.

**Comment by artwyman** [comment]
We've always limited ourselves to having Java create all the threads, which steps around this issue, as well as other issues we saw with native-created threads in the past.  You can see sample code for how we do that in [djinni/extension-libs/jni-exceptions](https://github.com/dropbox/djinni/tree/master/extension-libs/platform-threads).  @mknejp's library seems more flexible.

Regarding Java exceptions, the default code is set up only to ensure that exceptions get propagated, and can be passed back to Java, not anything more.  However there are pluggable functions (the ones declared weak) which you can replace without having to change the support library directly.  You can see a simple example of that in [djinni/extension-libs/jni-exceptions](https://github.com/dropbox/djinni/tree/master/extension-libs/jni-exceptions).  Internally we have a much more complicated version which knows about our custom exception types, and knows how to propagate stack traces between languages.  I talked a bit about it a bit at CppCon 2015, though the code isn't published because it's tied to our internal assumptions.  Note that we've always focused on getting the best diagnosability after propagating back to Java (since all our threads start there) rather than extracting maximal information in C++.

I'm going to close this issue since it doesn't seem to be a bug so much as a discussion of Djinni's limitations and techniques for improving them.  Feel free to continue the conversation, or to re-open if you think there are issues which need fixing.
