### ISSUE TITLE
Android: automate @Keep annotation

### ISSUE THREAD

**Issue by alexcohn** [dropbox/djinni#261]
Android Java dialect introduced `android.support.annotation.Keep` annotation to prevent obfuscation and shrinking Java classes and/or methods by _ProGuard_. It is necessary to give special instructions to _ProGuard_ for **djinni**-generated Java classes and methods, because _ProGuard_ cannot parse the C++ generated code, and does not know which classes will be referenced at runtime with `JniInterface` or `JniEnum` or `jniFindClass()` or `jniGetMethodID()`.

Usually we simply add the relevant classes into the **proguard-rules.pro** file in the root of the project:

    -keep class com.company.android_client.jni.** { *; }

But this does not work well when the project builds a library, not an app.

When such library is used in a 3<sup>rd</sup>-party app, _ProGuard_ runs again on the merged **jar** of all classes, and it will discard or obfuscate parts that are necessary for **djinni** to do its work.

So the logic should be, that any class that is referenced with `JniInterface` or `JniEnum` or `jniFindClass()`, and any method that is used for `jniGetMethodID()`, should be annotated with **`@Keep`**.

**Comment by mknejp** [comment]
Have you tried `--java-annotation`?
Run djinni with '--help' to get a list of all options (as mentioned in the README).

**Comment by alexcohn** [comment]
Well, for example I don't need **@Keep** on the abstract class, only on the **CppProxy** inner implementation class.

**Comment by mknejp** [comment]
I don't see how that matters. If the inner class is unobfuscated it means anyone can see the name of the outer class, so there is no point in obfuscating it. And since it is used as a base class (and parameter/return of methods) it cannot be stripped.

Furthermore any object extending the abstract class in a `+j` setting is a valid argument to Djinni-generated code so it requires the abstract class to be unobfuscated there as well.

We can't automatically add `@Keep` because Djinni is also used on desktop projects where the annotations are different. That's why users can customize the annotation depending on what tool they're using.

**Comment by artwyman** [comment]
Agreed with @mknejp.  The --java-annotation argument was added for exactly this purpose before android.support.annotation.Keep existed.  We use it in conjunction with app-level pro-guard rules like this (note JniGen was the pre-release internal name of Djinni):

-keep class com.dropbox.sync.android.annotations.JniGen
-keep @com.dropbox.sync.android.annotations.JniGen class *
-keepclassmembers @com.dropbox.sync.android.annotations.JniGen class *** {
	*;
}

Now that @Keep exists, you might be able to use it with --java-annotation as-is.  If not, I'd be open to tweaking the functionality of --java-annotation to work better with @Keep

**Comment by alexcohn** [comment]
Thanks, I believe that you are right. I will close this issue with relief.
