### ISSUE TITLE
About Djinni feature support

### ISSUE THREAD

**Issue by kinglezhuang** [dropbox/djinni#263]
Currently, I use Djinni for our project. Djinni is a great opensource project. But i met some problems.

1. Djinni Interface could not support class hierarchy. Swig or Jinjia can support that, but Djinni more convenience to define interface.
    Example: I have a base class & two subclasses, How can i use IDL file to define them.
    Do you have a plan to support this feature & when?
    Especially, Object-Oriented language without such feature can make code more complex.

2. I use 'interface +c' to define interface, the interface will be implemented in c++ & can be called from any language. But if i use 'interface +j +o' to define interface, the interface will be implemented in Java or Objective-C & can be called from C++. Most of time, Such interface is mainly used for c++ call specific platform features. For iOS, the generated objc file use 'protocol' to define interface, but for Android, why use 'abstract' to define abstract class, not use 'interface' to define interface. In Java, the class can not support multiple inheritance, only interface can support multiple inheritance. I think Java can keep the same semantic with iOS.

If Djinni can support above features, it can become more perfectly opensource project in the world.

**Comment by artwyman** [comment]
There have been prior discussions on both of these features.  I encourage you to join the Slack community mentioned in the README.md file for further discussion.

Brief answers:

1) Inheritance is a common feature request, and I'm in favor of adding it.  There's no particular schedule for doing so, though.  It's a matter of someone needing it enough to spend the time to implement it.  Pull Requests are welcome.
 2) The generated Java uses classes not interfaces because it needs a place to put static methods (not allowed in interfaces in Java until very recent versions) and the inner class for proxying +c implementations (which would be relevant for your use case if +c +j was used).  In theory, it would be possible to re-structure things to put those extra elements into a separate helper class, letting the primary class turn into an interface, but doing so would be a breaking change since people would need to change how they call static methods.  I wouldn't be against doing this, but again, it's a matter of someone wanting it enough to spend time on it. :)

I'm going to close out this issue since it's not really a good one for feature-request tracking, since it's 2 separate features.  If you want to submit two separate issues for the two feature requests, go ahead, and they can serve as a reminder and a place for future users to discuss.
