### ISSUE TITLE
Read-only fields for records

### ISSUE THREAD

**Issue by kinglezhuang** [dropbox/djinni#268]
Old Djinni Version:
Record's property can read-write for Objective C/Java/JNI code.

New Djinni Version:
Record's property can only read for Objective C/Java/JNI code.

**Comment by kinglezhuang** [comment]
my_record = record {
    id: i32;
    info: string;
    store: set<string>;
    hash: map<string, i32>;

    values: list<another_record>;

    # Comments can also be put here

    # Constants can be included
    const string_const: string = "Constants can be put here";
    const min_value: another_record = {
        key1 = 0,
        key2 = ""
    };
}

I think no 'const' keyword can read-write, and 'const' keyword can only read.
Change semantic cause our project hard to maintain.

**Comment by artwyman** [comment]
I don't understand whether you are claiming that something has changed in a way you dislike, or you are proposing a change.  Is this an issue you're seeing in production code, or just a theoretical question from looking at documentation and examples.  Can you clarify?  If Can you give sample code with expected behavior?

The const keyword in a Djinni record is for global constants, not constant fields.  It's equivalent to a "static const" or "constexpr" in C++.  Records have never had const fields in C++, because adding them would disable the ability to assign or move a record.  A record in C++ is intended to just be a bare struct with public fields and trival ctor/copy/move/dtor.  Note that records are always passed through Djinni calls by value (i.e. copied) so there's no risk of unexpected changes across the language boundary.  If you want an object with hidden data which you can control yourself, you can use an interface.  If you want a record not to be modified, you can declare the record variable const.

**Comment by kinglezhuang** [comment]
In Djinni Example[handwritter]:

Previous Version:
item_list = record {
    items: list<string>;
}

@interface TXSItemList : NSObject
- (id)initWithItemList:(TXSItemList *)itemList;
@property (nonatomic) NSMutableArray *items;
@end

public final class ItemList {
    public ArrayList<String> mItems;
    public ItemList(
            ArrayList<String> items,
            String name) {
        this.mItems = items;
    }
}

Current Version:

item_list = record {
    items: list<string>;
}

@interface TXSItemList : NSObject
- (nonnull instancetype)initWithItems:(nonnull NSArray<NSString *> *)items;
+ (nonnull instancetype)itemListWithItems:(nonnull NSArray<NSString *> *)items;

@property (nonatomic, readonly, nonnull) NSArray<NSString *> * items;

@end


public final class ItemList {

    /*package*/ final ArrayList<String> mItems;

    public ItemList(
            @Nonnull ArrayList<String> items) {
        this.mItems = items;
    }

    @Nonnull
    public ArrayList<String> getItems() {
        return mItems;
    }

    @Override
    public String toString() {
        return "ItemList{" +
                "mItems=" + mItems +
        "}";
    }
}


Now, we can not assign a value to property

**Comment by artwyman** [comment]
I'm interpreting this as a feature-request for read-only fields in records.  I don't think there's an issue with doing that for Java or ObjC, though it doesn't really impact the safety of the Djinni interface, so it seems like more a matter of style/preference.  I think the feature would be more questionable if applied to C++, due to the loss of ability to assign/move records.

**Comment by kinglezhuang** [comment]
Thank you Artwyman.

Because of our project use old version for record's property read-write, when we upgraded to new version, the code can not anymore, so i need to change record to interface & use accessor method to do that. Huge task.

**Comment by artwyman** [comment]
I'm sorry, we seem to be miscommunicating.  You're saying you want the properties to be read/write, and they used to be, but they're not anymore?  I don't recall that changing, but it may've been before I was maintainer.  Can you identify the "old version" you're referring to?  I thought you meant that was the current version, but you were asking for a new version to be created.  If that's incorrect, please clarify exactly which versions (identified by commit hash or date) you're referring to.

**Comment by artwyman** [comment]
Discussed on Slack and I think we cleared up the misunderstanding here.  Going to close out this issue, but feel free to re-open if after clarification you think there's a feature request you want tracked.

**Comment by xianwen** [comment]
Hahaha, Kingle, it's you!
