### ISSUE TITLE
How can I enable the use of std::experimental::optional or std::optional on Android?

### ISSUE THREAD

**Issue by csimmons0** [dropbox/djinni#291]
I'd like to use optionals, but I'm having trouble configuring the compiler or the STL to support them. How can I enable the use of std::optional or std::experimental::optional in my Android app? This is what the externalNativeBuild portion of my build.gradle presently looks like.
```
externalNativeBuild {
    cmake {
        arguments "-DANDROID_STL=c++_shared"
        cppFlags "-std=c++11", "-frtti", "-fexceptions"
    }
}
```

**Comment by artwyman** [comment]
I'm guessing that this quesiton is about how to make optional work on Android at all, not the specifics of making Djinn use it.  Let me know if you're looking for a different answer.

I can't give advice from direct expereince, since we actually use our own private copy, since we started using it before all compilers included it.  The one we use came from [here](https://github.com/akrzemi1/Optional).

However it looks like the header for optional is present both for gnul-libstdc++/4.9 and llvm-libc++/libcxx.  Does `#include <experimental/optional>` not work for you?  If not, I'd suspect you might need to tweak the NDK config to make sure it's using the right compiler and STL implementation.  We use ndk-build and GCC 4.9, so you'll need somewhat different settings for CMake and libc++, but it should be possible to make it work.  Sorry I can't be more immediately helpful.

**Comment by j4cbo** [comment]
Many stdlib implementations disable optional entirely with `-std=c++11` - you'll probably need to change the flag to `-std=c++14`. Not sure if that's sufficient but I'm pretty sure it's necessary.

**Comment by csimmons0** [comment]
Thanks. I wasn't able to get the STL to work, but I was able to use boost::optional, which was easy enough since it's a header-only library.

**Comment by aksswami** [comment]
@csimmons0 Can you provide some info on how did you integrated `boost::optional` with djinni? Djinni by default generate optional with `std::experimental::optional`, so to use <boost/optional> instead of that?

**Comment by artwyman** [comment]
There are cmdline arguments you can use to specify the string Djinni should use for the class name of `optional` as well as the header include.  Those should let you use `boost::optional` without any further changes.  You can see their definitions here: https://github.com/dropbox/djinni/blob/master/src/source/Main.scala#L138

**Comment by aksswami** [comment]
Thanks @artwyman, was able to use `boost::optional` header by using cmdline arguments. 

For others searching for the same:-
```
 --cpp-optional-header "\"<boost/optional/optional.hpp>\""
 --cpp-optional-template boost::optional
```
