### ISSUE TITLE
Wrong objc generated files

### ISSUE THREAD

**Issue by steweg** [dropbox/djinni#305]
Using this example:
```
MyInterface = interface +j {
  MyMethod1();
}

MyInterface2 = interface +j +o {
  MyMethod2();
}

MyInterface3 = interface +c {
  MyMethod3(inputInterface : MyInterface);
  MyMethod4(inputInterface : MyInterface2);
}
```

The generated code of objc files MyInterface+Private.mm is not able to be compiled and the source file doesn't includes the MyInterface+Private.h file. It also doesn't includes a bunch of other headers when compared to MyInterface2+Private.mm

Besides that, if I as a user of djinni don't expect that there will be no MyInterface implementation in Objc, I automatically expects that I will not be able to call MyMethod3, but there is currently no way to express this setting. Also currently generated code should not need to require existence of MyInterace+Private.h nor MyInterace+Private.mm (there will never be real implementation), but the generated code of MyInterface3+Private.mm expects "MyInterace+Private.h". I guess the best way would be here to provide only include for the public part and not private part

I tried to create my own PR for this (https://github.com/dropbox/djinni/pull/304), but during the testing it turned out that it is much more complicated for me to pin-point the right places, so please check it from your end. Thanks

**Comment by artwyman** [comment]
Hmm, are you sure you're on the latest version of Djinni?  I recall fixing for issues around this in the past.  It's not perfect because it still needs to generate unnecessary files, but everything should compile.  There's a test in the test-suite which covers this: https://github.com/dropbox/djinni/blob/master/test-suite/djinni/single_language_interfaces.djinni

I just confirmed that DBJavaOnlyListener* are generated and compiled properly.  If you're seeing different behavior, please give some more details.  You could push a branch with a modified version of the test suite which demonstrates your issue, and link to it here.

**Comment by steweg** [comment]
It turned out that you were right, I was working on my branch forked from your older "python" branch. It turned out that when I rebased to current one, it worked correctly
