### ISSUE TITLE
Anyone use djinni to create the obj/jni interfacefor Qt5  c++ api?

### ISSUE THREAD

**Issue by stereomatchingkiss** [dropbox/djinni#306]
As the question ask, do anyone tried to generate JNI/Obj-C interfaces of those classes written by Qt5? Is it possible to do? How should I deal with the event loop of Qt5? Almost every app written by Qt have their own event loop, should I expose the event loop class(QCoreApplication) by djinni?

Requirements of my project is create some sort of gps app, front end is done by react-native, backend could be done by anything. Up to now I think Qt5 provide most of the cross-platform c++ tools I need, gps support, network and database.

Someone may ask why not just use Qt5 to create the front end, the answer is politic issue.

**Comment by artwyman** [comment]
Djinni should be general enough for your needs, but it's intent is to bridge to custom-defined C++ classes defined by Djinni's IDL, not to bridge to pre-existing unmodified C++ libraries.  That's a different intent/philosophy from some other tools like SWIG, and was chosen so that the code looks native in all languages, rather than requiring "C-like" code in Java/ObjC.  So you can probably use Djinni to bridge from Java/ObjC to whatever Qt classes you want to use, but you'll probably have to implement your own C++ class as a layer in between.

FYI, for discussion and advice (rather than reporting issues) I'd suggest talking on the Slack community mentioned in the README.md file.  There's also a StackOverflow category for Djinni.
