### ISSUE TITLE
Djinni + Gmock issues due to forward declaration of structs

### ISSUE THREAD

**Issue by mamaral** [dropbox/djinni#335]
Gmock doesn't play nicely with forward-declared structs in interfaces, causing compiler issues. Is there any way to make it such that djinni generated interfaces add `#include "Foo.h"` instead of `struct Foo;`?

**Comment by artwyman** [comment]
I'm not deeply familiar with gmock, but is there any reason you couldn't just add `#include Foo.h` in the file which uses gmock, rather than in the Djinni-generated class file?  Djinni's trying to follow the rule of including the bare minimum, in order to minimize compile time.  An individual cpp file which uses a Djinni header can always include more things as it needs.

**Comment by michal-kowalczyk** [comment]
We might always create a special flag that will use forward declarations or includes. The question is if it is worth it?

**Comment by mamaral** [comment]
@artwyman Good point, that does work. We do run into this regularly, between enough different people on my team that it's always a bit to diagnose/resolve. I personally think it's worth it, but I wouldn't be the one doing the work, and it's probably not a massively common problem, so that one's up to you. :) Thank you!

**Comment by artwyman** [comment]
Glad that unblocks you.  My general philosophy would be not to put limitations or complexity in Djinni for things which can be resolved outside of it, so I'll leave this closed, at least unless it becomes a common problem.
