### ISSUE TITLE
f32

### ISSUE THREAD

**Issue by mknejp** [dropbox/djinni#34]
Hi,

at the CppCon talk you mentioned why there is only `f64`, something regarding inconsistent sizes across iOS architectures (it's been a while). However that only applies to `CGFloat` which is an alias to either `float` or `double`, depending on whether it runs on arm64 or not. The actual values of `sizeof(float)` and `sizeof(double)` always give `4` and `8`, respectively. On Java the aliases `jfloat` and `jdouble` already do the right thing.

So I'm not entirely sure I understand why there is only `f64`.

Regards
Miro

**Comment by lottototto** [comment]
+1
All (C++, Java, JNI and Obj-C) support float as primitive data type and it's size is 4 bytes. And it is supported by NSNubmer class. Any reason do not include f32?

Thank you.

**Comment by mbrgm** [comment]
+1

**Comment by artwyman** [comment]
I don't think C++ guarantees that float is always 4 bytes, so much as that it's at least 4 bytes.  Then I think the same is true for double and 8 bytes.  Unfortunately C++ doesn't supply floating-point equivalents of the fixed-width integer types (presumably because floating point accuracy is about more than just size).

I don't object to an f32 type, and I just confirmed that iOS does have consistent size of "float" on 32 vs. 64-bit platforms.  I think we just never had a case where we needed a floating point value and weren't willing to simply use an f64.

**Comment by mknejp** [comment]
Maybe it does make more sense to then drop the bit designation and stick to `float` and `double`. All the languages in Djinni's scope have these datatypes named the same, there is quite the legacy. As long as the generated code can reliable transform between C++ `float`/`double` and the foreign language types, everything is fine. I just see our code littered with `static_cast` in all interface classes because the entire model works with floats and takes them in its interface and we run with `-Weverything` so implicit narrowing leads to an explosion of warnings.
