### ISSUE TITLE
Problems with generating support lib

### ISSUE THREAD

**Issue by Aberrational** [dropbox/djinni#359]
I'm having problems with generating djinni support library for android.
I'm running the 
`cmake CMakeLists.txt`
that overrides the MakeFile and `make` makes something?
`libdjinni_support_lib.dylib`

But the project that I need djinni for expects a file per android architecture. 
Said project's CMakeLists.txt
`find_library(djinni NAMES djinni-support PATHS "${CMAKE_CURRENT_LIST_DIR}/lib/${CMAKE_ANDROID_ARCH_ABI}" 
` 
what should I do?

**Comment by Aberrational** [comment]
Sorry I was a little tired when i wrote that.

The issue (from a point of view of someone who is not familiar with some of the used tools) is the placement of CMakeLists.txt (I've seen a talk in a previous issue about the placement of this file and it might make sense to someone familiar with it but some instructions in README how to use it without destroying the normal files would be good)

The bonus question is about the artifact(s). Did something change or something has be done to get such artifacts.

**Comment by artwyman** [comment]
Hi, @Aberrational.  I'm not sure I can help directly here since I haven't used CMake.  We don't use it for Dropbox, so the CMake support in Djinni has been entirely contributed and maintained by the community.  It also sounds like you're mixing CMake and non-CMake builds, which might be an unusual use case.

I'd suggest joining the Slack community mentioned in the README to see if anyone there can help you debug your problem in more details.  Meanwhile I'm going to close out this issue, since it's more of a question than a bug, and I don't think GitHub is the best place to get answers.
