### ISSUE TITLE
Allow const methods on records

### ISSUE THREAD

**Issue by mpiannucci** [dropbox/djinni#369]
As is the only extra functionality a record can have across language bounds seems to be the builtin `derived` functions (`eq`, etc). 

It would be great if abstract method stubs could be created for records so that when records are extended on one side, the other languages can use the functionality. Like this ->

```
location = record +c {
    lat: f64;
    lon: f64;

    distance(other: location): f64;
}
```

which would give

```cpp
struct LocationBase {
    double lat;
    double lon;

    LocationBase(double lat_,
                 double lon_)
    : lat(std::move(lat_))
    , lon(std::move(lon_))
    {}

    virtual ~LocationBase() = default;

    virtual const double distance(const LocationBase& other) const = 0;

protected:
    LocationBase(const LocationBase&) = default;
    LocationBase(LocationBase&&) = default;
    LocationBase& operator=(const LocationBase&) = default;
    LocationBase& operator=(LocationBase&&) = default;
};
```

Its really more of a convenience thing than anything, but this is much more pleasant to code than to work with some static Extensions class or something that provides to extensions instead. 

I want to try to see if I can make this work, but if there are any pitfalls or the idea is unreasonable please let me know!

**Comment by artwyman** [comment]
I can see how this might be a convenient usage model.  What would you expect the implementation code to provide in each language, though?  If this is specifically for extended records, and you're expecting the extension to be present in some languages but not others, the generator would need to know something about that in order to fill in the gaps.

More fundamentally, I feel like this confuses the distinction between interfaces and records in ways which may be hard to understand.  Interfaces are for bridging, and each "object" always lives in only one language.  Records are for data, and objects are copied across languages.  If you called your `distance()` method on a record in Java, but the extension was implemented in C++, what would a user expect to happen?  Does the record get copied to C++ for each call?  Is the record expect to have a proxy object in C++ with its data kept in sync?  Does the record actually live in C++ with all accessors being bridged?  Any of those options have a cost, which could be hard to reason about.

When you know the details of your own specific use case, I think using static methods on an interface, and then calling them inside the extension class would be a reasonable approach.  That involves some "boiler plate" but the implementer of that boiler-plate gets to make the determination of what data is copied.  E.g. if your Location record also contained other data (name, photos taken in the location, whatever) the implementer could still pass only lat+lon which are needed for the distance calculation rather than marshalling the full record.

As an alternative, I wonder if what you're really looking for here is an interface (lives in one language, with bridged methods) but with data fields.  That can be done by hand today by declaring your own accessors and mutators, but there's been discussion in the past of adding a feature similar to ObjC's "properties" to auto-generate accessors/mutators from a field declaration.  That would be cheaper to copy but more expensive to call each individual accessor when compared to a record.

**Comment by mpiannucci** [comment]
Thanks for the reply! 

My original idea was basically to only allow the methods to be defined when the record is marked with `+c`. Basically just allowing for read only computed properties in records. After researching a bit more and reading through the source a bit, I think I am trying to work with a flawed idea and there are better architectures (Using a ViewModel created in C++, etc) that can just take advantage of the existing record extension functionality. Which sounds like what you mentioned with using interfaces instead. 

I think I misunderstood that records are copied across bounds always but interfaces are not, which would make this idea pretty useless from the way I was thinking about it. Going to close, thanks
