### ISSUE TITLE
C++/Java interop on Linux/MacOSX

### ISSUE THREAD

**Issue by migel** [dropbox/djinni#72]
Hi, I've tried to use djinni for calling C++ from Java on both Linux and MaxOSX but I get a ```java.lang.UnsatisfiedLinkError``` exception at runtime.  Is it supposed to be possible to use the C++/Java interop functionality of djinni on Linux and MaxOSX or is the implementation specific to the Android build/runtime system?

**Comment by j4cbo** [comment]
There's nothing specific to Android, but Djinni doesn't take care of actually loading the library for you. It definitely works on OS X since that's where I run the unit tests, and should work on Linux too.

Take a look at the `test-suite/java` directory; running `ant test` there should build and run some sample stuff for you (you'll need to `run_djinni.sh` in the parent dir first). In particular note the `System.loadLibrary` call at https://github.com/dropbox/djinni/blob/master/test-suite/handwritten-src/java/com/dropbox/djinni/test/AllTests.java#L24

**Comment by migel** [comment]
Hi, It turns out I didn't generate the jni files just the cpp files so that was the source of my problem. I got it to run on both MaxOSX and Linux. Thanks.
