### ISSUE TITLE
iOS c++11 is not supported

### ISSUE THREAD

**Issue by wqwu** [dropbox/djinni#79]
there is an error: 'auto' not allowed in lambda parameter after updated to latest djinni, i.e
```c++
  auto Api::fromCpp(const CppType& cpp) -> ObjcType
  {
      return !cpp ? nil : ::djinni::DbxCppWrapperCache<::jg_gen::Api>::getInstance()->get(cpp, [] (const auto& p)
      {
          return [[JGApi alloc] initWithCpp:p];
      });
  }
```

the issue is from "[] (const auto& p".

if i change objc project setting to c++14 seems ok, but our code need to compile in visual studio, c++14 maybe has some risk.

is this by design ?

**Comment by mknejp** [comment]
This is in Objective-C++ only `.mm` files, so Visual Studio is never going to see them. You can enable C++14 for selected files only in Xcode in the project settings -> `Build Phases` -> `Compile Sources` then double click on the far right of a column and add `-std=c++14` as a temporary solution until I get #74 updated to the newest master where removing the C++14 dependencies will be a priority since there seem to be several people who have problems with it.

**Comment by mknejp** [comment]
You might want to check #80 if that fixes your problem. If not then there's a C++14 dependency somewhere else that I overlooked.

**Comment by wqwu** [comment]
thanks, Miro. I already updated to latest code, that fixed issue,.
